// lib/firebase_options.dart
// File generated by FlutterFire CLI.

// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDzqlnZD15IBozvWGVZoukhV1YzvlLCDOY',
    appId: '1:450840113644:web:770c6fc7ee8e250b7790c9',
    messagingSenderId: '450840113644',
    projectId: 'bubblepop-chat',
    authDomain: 'bubblepop-chat.firebaseapp.com',
    storageBucket: 'bubblepop-chat.appspot.com',
    measurementId: 'G-NT4J2NZJ4N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB94cH_JqjBWXnp_xUPUUX9mUoz57uipO0',
    appId: '1:450840113644:android:89a7705e7bbbdcb97790c9',
    messagingSenderId: '450840113644',
    projectId: 'bubblepop-chat',
    storageBucket: 'bubblepop-chat.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAcNUm4YZ1uXzVKIOWm-TLYWEXpqRBaNQw',
    appId: '1:450840113644:ios:93bb9121097ff1a47790c9',
    messagingSenderId: '450840113644',
    projectId: 'bubblepop-chat',
    storageBucket: 'bubblepop-chat.firebasestorage.app',
    iosBundleId: 'com.example.popchat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAcNUm4YZ1uXzVKIOWm-TLYWEXpqRBaNQw',
    appId: '1:450840113644:ios:93bb9121097ff1a47790c9',
    messagingSenderId: '450840113644',
    projectId: 'bubblepop-chat',
    storageBucket: 'bubblepop-chat.firebasestorage.app',
    iosBundleId: 'com.example.popchat',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDzqlnZD15IBozvWGVZoukhV1YzvlLCDOY',
    appId: '1:450840113644:web:fa6e5aef0d29df687790c9',
    messagingSenderId: '450840113644',
    projectId: 'bubblepop-chat',
    authDomain: 'bubblepop-chat.firebaseapp.com',
    storageBucket: 'bubblepop-chat.firebasestorage.app',
    measurementId: 'G-LDCSQ973C3',
  );
}
